name: photos
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.9.0
  google_fonts: ^6.1.0
  get: ^4.6.6
  flutter_svg: ^2.0.9
  tuple: ^2.0.2
  on_process_button_widget: ^2.0.2
  get_storage: ^2.1.1

  http: ^1.1.2
  intl: ^0.19.0
  on_popup_window_widget: ^0.0.8
  win32: ^5.9.0

  #! Needs Native support
  fluttertoast: ^8.2.4 # Needed native support
  permission_handler: ^11.0.1
  path_provider: ^2.1.5
  share_plus: ^10.1.4
  dio: ^5.8.0+1
  flutter_localizations:
    sdk: flutter
  go_router: ^15.0.0

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  dart_code_metrics: any
  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true



  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
